'use client';import{useEffect,useState}from"react";import{useRouter}from"next/navigation";
const empty={company:"",title:"",dates:"",bullets:[""]};const projectEmpty={name:"",description:"",technologies:[""]};
export default function Profile(){const[p,setP]=useState<any>({skills:[],certifications:[],experiences:[],projects:[],education:[]}),[saved,setSaved]=useState(""),r=useRouter();useEffect(()=>{fetch("/api/profile").then(async x=>x.ok?setP(await x.json()):r.push("/login"))},[]);
const set=(k:string,v:any)=>setP((x:any)=>({...x,[k]:v}));const add=(k:string,item:any)=>set(k,[...(p[k]||[]),item]);const remove=(k:string,i:number)=>set(k,p[k].filter((_:any,n:number)=>n!==i));const update=(k:string,i:number,field:string,v:any)=>set(k,p[k].map((x:any,n:number)=>n===i?{...x,[field]:v}:x));
async function save(){const x=await fetch("/api/profile",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)});setSaved(x.ok?"Saved successfully":"Save failed")}
return <main className="shell"><nav className="nav"><div><div className="brand">JD Resume AI</div><h1>Master Resume</h1></div><a href="/dashboard" className="btn alt">Dashboard</a></nav>
<section className="card"><h2>Personal information</h2><div className="grid">{["headline","phone","location","linkedin","website"].map(k=><div className="field" key={k}><label>{k}</label><input value={p[k]||""} onChange={e=>set(k,e.target.value)}/></div>)}</div><div className="field"><label>Professional summary</label><textarea value={p.summary||""} onChange={e=>set("summary",e.target.value)} /></div></section>
<section className="card" style={{marginTop:18}}><h2>Skills</h2><div>{(p.skills||[]).map((x:string,i:number)=><span className="pill" key={i}>{x} <button onClick={()=>remove("skills",i)}>×</button></span>)}</div><button className="btn alt" onClick={()=>add("skills","")}>+ Add skill</button></section>
<section className="card" style={{marginTop:18}}><h2>Experience</h2>{(p.experiences||[]).map((x:any,i:number)=><div className="card" key={i} style={{marginTop:12}}><div className="grid"><div className="field"><label>Company</label><input value={x.company||""} onChange={e=>update("experiences",i,"company",e.target.value)}/></div><div className="field"><label>Job title</label><input value={x.title||""} onChange={e=>update("experiences",i,"title",e.target.value)}/></div></div><div className="field"><label>Dates</label><input value={x.dates||""} onChange={e=>update("experiences",i,"dates",e.target.value)}/></div><div className="field"><label>Achievement / responsibility bullets</label><textarea value={(x.bullets||[]).join("\n")} onChange={e=>update("experiences",i,"bullets",e.target.value.split("\n"))}/></div><button className="btn alt" onClick={()=>remove("experiences",i)}>Remove</button></div>)}<button className="btn" onClick={()=>add("experiences",{...empty,bullets:[""]})}>+ Add experience</button></section>
<section className="card" style={{marginTop:18}}><h2>Projects</h2>{(p.projects||[]).map((x:any,i:number)=><div className="card" key={i} style={{marginTop:12}}><div className="field"><label>Project name</label><input value={x.name||""} onChange={e=>update("projects",i,"name",e.target.value)}/></div><div className="field"><label>Description</label><textarea value={x.description||""} onChange={e=>update("projects",i,"description",e.target.value)}/></div><div className="field"><label>Technologies (comma separated)</label><input value={(x.technologies||[]).join(", ")} onChange={e=>update("projects",i,"technologies",e.target.value.split(",").map((s:string)=>s.trim()).filter(Boolean))}/></div><button className="btn alt" onClick={()=>remove("projects",i)}>Remove</button></div>)}<button className="btn" onClick={()=>add("projects",{...projectEmpty,technologies:[""]})}>+ Add project</button></section>
<section className="card" style={{marginTop:18}}><h2>Certifications & Education</h2><div className="field"><label>Certifications (one per line)</label><textarea value={(p.certifications||[]).join("\n")} onChange={e=>set("certifications",e.target.value.split("\n").filter(Boolean))}/></div><div className="field"><label>Education (one per line)</label><textarea value={(p.education||[]).join("\n")} onChange={e=>set("education",e.target.value.split("\n").filter(Boolean))}/></div></section>
<div style={{position:"sticky",bottom:16,marginTop:18}}><button className="btn" onClick={save}>Save Master Resume</button> <span className="success">{saved}</span></div></main>