'use client';import{useEffect,useState}from"react";import{useRouter}from"next/navigation";
export default function Dashboard(){const[u,setU]=useState<any>(null),[jd,setJd]=useState(""),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),r=useRouter();
useEffect(()=>{fetch("/api/me").then(async x=>x.ok?setU(await x.json()):r.push("/login"))},[]);
async function generate(){if(jd.trim().length<80)return;setBusy(true);setMsg("Reading JD → researching role → optimizing ATS keywords → generating documents...");const x=await fetch("/api/jobs/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({description:jd})});const d=await x.json();setBusy(false);if(!x.ok){setMsg(d.error||"Generation failed");return}r.push("/job/"+d.jobId)}
if(!u)return <main className="shell"><div className="card">Loading...</div></main>;
return <main className="shell"><nav className="nav"><div><div className="brand">JD Resume AI</div><div className="muted">AI Resume Tailoring Studio</div></div><div><span className="pill">{u.credits} free credits</span>{u.role==="ADMIN"&&<> <a className="btn alt" href="/admin">Admin</a></>} <button className="btn alt" onClick={async()=>{await fetch("/api/auth/logout",{method:"POST"});r.push("/login")}}>Logout</button></div></nav>
<div className="layout"><aside className="sidebar"><a href="/dashboard">✦ New Application</a><a href="/profile">▣ Master Resume</a><a href="/dashboard">◷ Applications</a></aside>
<section><div className="card hero"><h1>Tailor your resume to any JD</h1><p className="muted">Paste a US job description. The engine extracts ATS requirements, researches the role, then rewrites your resume and cover letter around the strongest relevant parts of your real profile.</p>
<div className="field"><label><strong>Job Description</strong></label><textarea value={jd} onChange={e=>setJd(e.target.value)} placeholder="Paste the complete job description here..."/></div>
<button className="btn" disabled={busy||jd.trim().length<80} onClick={generate}>{busy?"Generating...":"Generate Tailored Resume + Cover Letter"}</button><p className="muted">{msg}</p></div>
<div className="stats" style={{marginTop:16}}><div className="stat"><strong>JD-first</strong><span className="muted">Keywords & responsibilities</span></div><div className="stat"><strong>ATS</strong><span className="muted">Transparent matching</span></div><div className="stat"><strong>DOCX</strong><span className="muted">Ready to download</span></div></div></section></div></main>}